[project]
name = "signbridge-3d-vsl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "flask>=3.1.3",
    "numpy>=2.5.3",
    "opencv-python>=5.0.0.93",
    "requests>=2.34.2",
    "scipy>=1.18.1",
    "torch>=2.14.1",
    "torchvision>=0.29.1",
    "websocket-client>=1.9.2",
]
